"""users table

Revision ID: 6b688fe63768
Revises: 
Create Date: 2019-01-15 13:50:06.196868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b688fe63768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinamica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('p_inicial', sa.Float(), nullable=True),
    sa.Column('t_inicial', sa.Float(), nullable=True),
    sa.Column('p_ref', sa.Float(), nullable=True),
    sa.Column('t_atingir_ref', sa.Float(), nullable=True),
    sa.Column('f_atingir_ref', sa.Float(), nullable=True),
    sa.Column('t_estavel', sa.Float(), nullable=True),
    sa.Column('p_ensaio', sa.Float(), nullable=True),
    sa.Column('t_atingir_ensaio', sa.Float(), nullable=True),
    sa.Column('f_atingir_ensaio', sa.Float(), nullable=True),
    sa.Column('t_final', sa.Float(), nullable=True),
    sa.Column('estado', sa.Float(), nullable=True),
    sa.Column('pressao', sa.Float(), nullable=True),
    sa.Column('temperatura', sa.Float(), nullable=True),
    sa.Column('UR', sa.Float(), nullable=True),
    sa.Column('pwm_valvula_pressao', sa.Integer(), nullable=True),
    sa.Column('pwm_valvula_vacuo', sa.Integer(), nullable=True),
    sa.Column('status_bomba', sa.Integer(), nullable=True),
    sa.Column('status_pid', sa.Integer(), nullable=True),
    sa.Column('setpoint', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ensaios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('pressao_referencia', sa.Integer(), nullable=False),
    sa.Column('tempo_atingir_referencia', sa.Integer(), nullable=False),
    sa.Column('tempo_estavel_referencia', sa.Integer(), nullable=False),
    sa.Column('pressao_de_ensaio', sa.Integer(), nullable=False),
    sa.Column('tempo_atingir_ensaio', sa.Integer(), nullable=False),
    sa.Column('ativacao_data', sa.String(length=10), nullable=False),
    sa.Column('ativacao_hora', sa.String(length=10), nullable=False),
    sa.Column('desativacao_data', sa.String(length=10), nullable=False),
    sa.Column('desativacao_hora', sa.String(length=10), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_bomba', sa.Integer(), nullable=True),
    sa.Column('status_pid', sa.Integer(), nullable=True),
    sa.Column('pwm_valvula_pressao', sa.Integer(), nullable=True),
    sa.Column('pwm_valvula_vacuo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('pressao', sa.Float(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('UR', sa.Float(), nullable=False),
    sa.Column('pwm_valvula_pressao', sa.Integer(), nullable=False),
    sa.Column('pwm_valvula_vacuo', sa.Integer(), nullable=False),
    sa.Column('status_bomba', sa.Integer(), nullable=False),
    sa.Column('status_pid', sa.Integer(), nullable=False),
    sa.Column('setpoint', sa.Float(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kp', sa.Float(), nullable=False),
    sa.Column('kd', sa.Float(), nullable=False),
    sa.Column('ki', sa.Float(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pid')
    op.drop_table('medidas')
    op.drop_table('manual')
    op.drop_table('ensaios')
    op.drop_table('dinamica')
    # ### end Alembic commands ###
